server.port=${PORT:8080}
spring.application.name=movie-rate
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mainline.proxy.rlwy.net:15113/railway}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:xBljBAZoczWdzgXftFiKdTlYCSnNDvWm}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
jwt=${JWT:unesecretcletreslonguepourletestjwths256minimum32chars!}
jwt.exp=${JWT_EXP:3600000}